services:
  - type: web
    name: firezone3-backend
    runtime: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: FRONTEND_URL
        value: https://paras1706.github.io
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
